site_name: GraphHopper Directions API Documentation
site_description: GraphHopper Directions API
site_favicon: https://graphhopper.com/favicon.ico
docs_dir: .
pages:
- Overview: index.md
- API parts:
  - Routing API: routing.md
  - Route Optimization API: route-optimization.md  
  - Geocoding API: geocoding.md
  - Map Matching API: map-matching.md
  - Isochrone API: isochrone.md
  - Matrix API: matrix.md
- Attribution: attribution.md
- Vehicles: supported-vehicle-profiles.md
- FAQ: FAQ.md
extra_css: 
  - css/custom.css
extra_javascript:
  - js/custom.js
theme: flatly